# Generated by Django 2.2.28 on 2023-01-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
