# Generated by Django 4.1.7 on 2023-04-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_auto_20230122_1820"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="zipcode",
            field=models.IntegerField(),
        ),
    ]
